# Generated by Django 5.0.6 on 2024-06-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('law', 'Law'), ('architecture', 'Architecture'), ('fashion', 'Fashion'), ('entertainment', 'Entertainment'), ('hospitality', 'Hospitality'), ('restaurant', 'Restaurant'), ('jewelry', 'Jewelry'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_in_company',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('director', 'Director'), ('representative', 'Representative'), ('broker', 'Broker'), ('ceo', 'CEO'), ('co-founder', 'Co-Founder'), ('executive', 'Executive'), ('founder', 'Founder'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_type',
            field=models.CharField(blank=True, choices=[('investment_fund', 'Investment Fund'), ('family_office', 'Family Office'), ('individual', 'Individual'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_type',
            field=models.CharField(blank=True, choices=[('accountant', 'Accountant'), ('appraiser', 'Appraiser'), ('architect', 'Architect'), ('boiler', 'Boiler'), ('carpentry', 'Carpentry'), ('cctv', 'CCTV (Security Cameras)'), ('doors', 'Doors'), ('earthwork', 'Earthwork'), ('electrical', 'Electrical'), ('elevator', 'Elevator'), ('event_planner', 'Event Planner'), ('flooring', 'Flooring'), ('foundation', 'Foundation'), ('framing', 'Framing'), ('general_contractor', 'General Contractor'), ('general_repairs', 'General Repairs'), ('hvac', 'HVAC'), ('inspector', 'Inspector'), ('interior_designer', 'Interior Designer'), ('it', 'IT'), ('landscaping', 'Landscaping'), ('lawyer', 'Lawyer'), ('marketing', 'Marketing'), ('mechanical', 'Mechanical'), ('metal_work', 'Metal Work'), ('moving', 'Moving'), ('paint', 'Paint'), ('plumbing', 'Plumbing'), ('roofing', 'Roofing'), ('scaffolding', 'Scaffolding'), ('sitework_protection', 'Sitework Protection'), ('violation_resolution', 'Violation Resolution'), ('windows', 'Windows'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('broker_real_estate', 'Broker (Real Estate)'), ('broker_mortgage', 'Broker (Mortgage)'), ('owner', 'Owner'), ('lender', 'Lender'), ('service_provider', 'Service Provider'), ('tenant', 'Tenant')], max_length=100),
        ),
    ]
