# Generated by Django 5.0.6 on 2024-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_industry_customuser_mailing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lender_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
