# Generated by Django 5.0.6 on 2024-06-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_lender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='established',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
