# Generated by Django 5.0.6 on 2024-07-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenant_subtype',
            field=models.CharField(blank=True, choices=[('COMPANY', 'company'), ('EMPLOYEE', 'employee')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'residential'), ('COMMERCIAL', 'commercial')], max_length=100, null=True),
        ),
    ]
