# Generated by Django 5.0.6 on 2024-07-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_tenant_subtype_customuser_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant_subtype',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('employee', 'Employee')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('broker_real_estate', 'Broker (Real Estate)'), ('broker_mortgage', 'Broker (Mortgage)'), ('owner', 'Owner'), ('lender', 'Lender'), ('service_provider', 'Service Provider'), ('tenant', 'Tenant'), ('salesperson_real_estate', 'Salesperson (Real Estate)'), ('salesperson_mortgage', 'Salesperson (Mortgage)')], max_length=100),
        ),
    ]
