# Generated by Django 5.0.6 on 2024-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_tenant_subtype_customuser_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
    ]
