# Generated by Django 5.0.6 on 2024-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant_subtype',
            field=models.CharField(blank=True, choices=[('company', 'COMPANY'), ('employee', 'EMPLOYEE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('residential', 'RESIDENTIAL'), ('commercial', 'COMMERCIAL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('broker_real_estate', 'Broker (Real Estate)'), ('broker_mortgage', 'Broker (Mortgage)'), ('salesperson_real_estate', 'Salesperson Real Estate'), ('owner', 'Owner'), ('lender', 'Lender'), ('service_provider', 'Service Provider'), ('tenant', 'Tenant')], max_length=100),
        ),
    ]
