# Generated by Django 5.0.6 on 2024-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_tenant_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('broker_real_estate', 'Broker (Real Estate)'), ('broker_mortgage', 'Broker (Mortgage)'), ('salesperson_real_estate', 'Salesperson Real Estate'), ('salesperson_mortgage', 'Mortgage salesperson'), ('owner', 'Owner'), ('lender', 'Lender'), ('service_provider', 'Service Provider'), ('tenant', 'Tenant')], max_length=100),
        ),
    ]
