# Generated by Django 5.0.6 on 2024-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
