# Generated by Django 5.0.6 on 2024-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_phonenumber_directory_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
