# Generated by Django 5.0.6 on 2024-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_directory_userfile_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('investment_fund', 'Investment Fund'), ('family_office', 'Family Office'), ('individual', 'Individual'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.phonenumber'),
        ),
    ]
