# Generated by Django 5.0.6 on 2024-08-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_phonenumber_fax_phonenumber_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='fax',
        ),
    ]
