# Generated by Django 5.0.6 on 2024-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_phonenumber_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='users.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='users', to='users.phonenumber'),
        ),
    ]
