# Generated by Django 5.0.6 on 2024-08-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_companies_customuser_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.companytype'),
        ),
    ]
