# Generated by Django 5.0.6 on 2024-08-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_lendertype_remove_customuser_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lender_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lendertype'),
        ),
    ]
