# Generated by Django 5.0.6 on 2024-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('looking_at', 'Looking At'), ('archived', 'Archived')], default='looking_at', max_length=20),
        ),
    ]
