# Generated by Django 5.0.6 on 2024-07-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('my_property', 'My property'), ('looking_at', 'Looking At'), ('archived', 'Archived')], default='my_property', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
