# Generated by Django 5.0.6 on 2024-07-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_property_type_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype'),
        ),
    ]
