# Generated by Django 5.0.6 on 2024-07-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('My_property', 'My Property'), ('Looking_at', 'Looking At'), ('Archived', 'Archived')], default='my_property', max_length=20),
        ),
    ]
