# Generated by Django 5.0.6 on 2024-06-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='property_unit',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.DeleteModel(
            name='PropertyUnit',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
