# Generated by Django 5.0.6 on 2024-07-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_ll_name', models.CharField(max_length=255)),
                ('ll_nickname', models.CharField(max_length=255)),
                ('how_often', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=50)),
                ('standard_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveIntegerField()),
                ('floor', models.CharField(blank=True, max_length=255)),
                ('government_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalLawContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_contact', models.CharField(blank=True, max_length=255)),
                ('respondent', models.CharField(blank=True, max_length=255)),
                ('other', models.CharField(blank=True, max_length=255)),
                ('local_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='local_law.locallaw')),
            ],
        ),
        migrations.CreateModel(
            name='LocalLawDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('service_date', models.DateTimeField()),
                ('local_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='local_law.locallaw')),
            ],
        ),
        migrations.CreateModel(
            name='LocalLawField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('local_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='local_law.locallaw')),
            ],
        ),
        migrations.CreateModel(
            name='LocalLawNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField(blank=True)),
                ('shared', models.TextField(blank=True)),
                ('local_law', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='local_law.locallaw')),
            ],
        ),
    ]
