# Generated by Django 5.0.6 on 2024-07-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_number', models.CharField(max_length=255)),
                ('issuing_agency', models.CharField(max_length=255)),
                ('agency_violation_number', models.CharField(max_length=255)),
                ('issued_to', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('standard_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('face_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('court_decision', models.CharField(max_length=255)),
                ('government_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='violations.violation')),
            ],
        ),
    ]
